### PR TITLE
Automate testing of quickstart tutorial

### PR DESCRIPTION
**Pull request by freesig**
Trying to automate the testing of the quickstart tutorial.

### CODE REVIEW

**Comment by dhtnetwork** [comment]
Error message:  Step nix-env -f https://holochain.love -iA holochain.holochain holochain.hc
I don’t recall holochain.holochain holochain.hc in previous quick start iterations.  

Not able to proceed. I tried this command twice: nix-env -f https://holochain.love -iA holochain.holochain holochain.hc  same error message.
Screen Shot 2019-08-07 at 04 00 34

**Comment by thedavidmeister** [comment]
@dhtnetwork what version of xcode do you have?

**Comment by thedavidmeister** [comment]
@dhtnetwork @zippy i noticed that `hc test` relies on `cargo` which means that it's not particularly useful outside holonix

sure, i can use `nix-env` to install it but then it tries to dial out to things that are probably not installed on the host environment

what are the benefits of `hc XXX` vs `hn-XXX` as a holonix command?

@yegortimoshenko is this a use-case for `makeWrapper`? should we try to wrap `hc` with a cargo dependency?

**Comment by thedavidmeister** [comment]
@dhtnetwork it's passing tests here :thinking: 

circle is using xcode: "10.2.0"

**Comment by dhtnetwork** [comment]
@thedavidmeister remember I am putting myself in the shoes of a user. downloading it for the 1st time (even though I have gone through similar install processes many times). So if it's not in the instructions, then they would not know. Its a matter of including that in the instructions.

**Comment by dhtnetwork** [comment]
Since we plan to include the system requirements info, then I think it will be clear for people to install xcode.

**Comment by thedavidmeister** [comment]
@dhtnetwork it is in the instructions and has been since we reviewed it

image

**Review by dhtnetwork — APPROVED** [review]

**Pull request merged**
