### PR TITLE
VS code RLS extension support

### PR DESCRIPTION
**Pull request by pospi**

### CODE REVIEW

**Comment by pospi** [comment]
FWIW this is needed for various editor tooling (eg. VS Code RLS extension) to function. May be further additions necessary.

**Comment by thedavidmeister** [comment]
@pospi could you give some more info on why this is needed?

@samrose and @yegortimoshenko had ideas for getting IDE support based on how it has been handled in other languages

the main thing i see is that `rustup` tries to put things in `~/.cargo/bin` and puts that on your path, including versions of the rust compiler itself, and that overrides the nix version of the rust compiler

the default rustup behaviour breaks the ability to use the nix provided compiler in the shell

**Comment by lukateras** [comment]
So, by default, `rls-vscode` does seem to throw an error when `rustup` is not available: https://github.com/rust-lang/rls-vscode/blob/db9d51db50f263234c73693691b646fe7a681656/src/rustup.ts#L84-103

@pospi I wonder if setting `rust-client.disableRustup` to `false` could work for you: https://github.com/rust-lang/rls-vscode/blob/6f65f3b4af86ba24625b313b1341686595ec9972/src/configuration.ts#L90-L96

The problem with offering `rustup` as part of development environment is that Holonix manages specific version of Rust via Nix, and that is going to be somewhat custom soon (needs a patch cherry-picked from `master` that fixes `rustfmt` `async/await` handling). As such, if someone's development environment would actually use `rustup` to set up specific versions and such, that is not going to work.

> @samrose and @yegortimoshenko had ideas for getting IDE support based on how it has been handled in other languages

Sure: I referred to writing something like [`nix-buffer`](https://github.com/shlevy/nix-buffer) for every IDE that Holochain developers use. For VS Code specifically, good place to start would be https://github.com/microsoft/vscode-remote-release/issues/554.

**Review by thedavidmeister — CHANGES_REQUESTED** [review]
so VS is getting a lot of love on the poll over here - https://www.reddit.com/r/holochain/comments/cjme4a/whats_your_favorite_ide/

@yegortimoshenko @pospi if we could land a non-rustup solution that would be very cool

**Comment by pospi** [comment]
Version management stuff totally makes sense. I think it's fine to reject this PR and close it (seems to be working for me with latest holonix & that VSCode config switch), but can I make the request that someone file an issue to document the `rust-client.disableRustup` option in the Holochain docs? In my experience if tooling is broken, devs (including Holochain devs) will just operate without it and have their effectiveness hampered unknowingly.

**Comment by thedavidmeister** [comment]
@pospi very true, i'm working on docs over here https://github.com/holochain/holonix/pull/41

there's a section on IDE support that i haven't written yet but i'll incorporate the feedback from this thread when i do :+1: 

really good to hear that it works :)

**Comment by arrterian** [comment]
@yegortimoshenko
I released an experimental extension for working with nix environments in vs code.
You can set own shell.nix confix, then all extensions and the main process will obtain the env. It's working using nix-shell under the hood.
It can be a little buggy at the moment.

If you are interested, welcome :)
https://marketplace.visualstudio.com/items?itemName=arrterian.nix-env-selector

**Comment by thedavidmeister** [comment]
i included the `rust-client.disableRustup` and `nix-env-selector` options in the docs branch under the IDE section

i think we are OK to close this PR now

**Pull request closed without merging**
