### PR TITLE
Add draft Dockerfile.manjaro

### PR DESCRIPTION
**Pull request by jameschrray**
The last step with nix-shell https://holochain.love doesn't work as shown at https://pastebin.com/FE98je25

### CODE REVIEW

**Comment by jamesray1** [comment]
See also https://discourse.nixos.org/t/warning-nix-search-path-entry-nix-var-nix-profiles-per-user-root-channels-does-not-exist-ignoring/5170/4.

**Comment by thedavidmeister** [comment]
@jamesray1 i see a lot of "no such file or directory" for things prefixed with `/build/*` does that dir exist?

**Comment by jamesray1** [comment]
I don't know, but I've done some additional work on this and will push changes, probably once I get it all working.

**Comment by thedavidmeister** [comment]
@jameschrray great, also if you can get something running on circle for at least this branch then we can both look at the failures without you needing to copy and paste logs

**Comment by jamesray1** [comment]
See #127

**Pull request closed without merging**
