### PR TITLE
Manjaro dockerfile

### PR DESCRIPTION
**Pull request by jameschrray**

### CODE REVIEW

**Comment by jameschrray** [comment]
~~Hmm, looks like it may be best to add the changes to config.yml in a separate PR.~~

**Comment by jameschrray** [comment]
See https://github.com/holochain/holonix/pull/128

**Comment by jameschrray** [comment]
Discussion also is at https://discourse.nixos.org/t/error-with-building-a-dockerfile-for-holochain-in-a-nix-shell-error-opening-lock-file-home-docker-nix-profile-lock-permission-denied/5246.

**Comment by thedavidmeister** [comment]
@jameschrray so the docker build is not currently running on circleci here due to the filter on the job that restricts it to branches that are not this branch

could we remove the branch filter so we can see it running here?

**Comment by jamesray1** [comment]
@thedavidmeister rather than removing the filters I added this branch to specific builds. Not sure if that's what is best but I did it anyway. Feel free to add commits/PRs to any of my PRs.

**Comment by thedavidmeister** [comment]
@jameschrray hmm it's still not building, is `requires:ld` intentional?

**Comment by thedavidmeister** [comment]
hmm that's weird @mmahut can you look into why this is not triggering builds? maybe circle is not configured

**Comment by mmahut** [comment]
@thedavidmeister as I do not have admin access to circleCI, I can guess that this can be related to:

- passing secrets to build from pull requests disabled, or:
- changes to `.circleci/config.yml` not allowed to non-admin users?

**Comment by steveej** [comment]
@jameschrray This PR looks like it is stale. Would you still like to pursue it or shall we close it?

**Pull request closed without merging**
