### PR TITLE
creates a running happ :)

### PR DESCRIPTION
**Pull request by philipbeadle**
Bash script to create a runnign happ from the react-graphql-template repo.

### CODE REVIEW

**Comment by thedavidmeister** [comment]
@philipbeadle looks like there's a flaky test on mac?

**Review by thedavidmeister — APPROVED** [review]
seems like a good start, there's some things hardcoded here like folder paths that could be iterated on to be more flexible but i think we can use this as a good base

**Comment by philipbeadle** [comment]
Yep, now you can pass project name and zome name.

**Review by thedavidmeister — APPROVED** [review]

**Comment by robbiecarlton** [comment]
@philipbeadle - ready to merge this?

**Comment by zippy** [comment]
1. From what I can tell this won't actually work if used yet because [react-graphql dna pointing to the wrong place](https://github.com/holochain/react-graphql-template/blob/master/dna_src/zomes/notes/code/Cargo.toml)

I have made pull requests [here](https://github.com/holochain/holochain_anchors/pull/8) and [here](https://github.com/holochain/react-graphql-template/pull/16) that I think fix that.

2. The fn hn-happ-create does much more than create the happ, it also spins it up and runs it, which was confusing to me because you see the error logs spinning out of both a sim2h server and the recact server (I think) all the while that it's building a happ.   I would think that there should be a create step, and separate run step.

3. There are no tests for hn-happ-create itself, so we can't tell that its actually even working in the CI.  Adding tests would mean adding something like or to the test/nix-env.sh file that proves out that the command actually does what's expected.  I think that might likely be difficult/impossible given all the stuff that it fires up!  Another reason perhaps at least to split hn-happ-create into create and run?

I don't want to block the merge but I think that is pretty weird for something that's supposed to be intuitive to first time users.  @pdaoust ?

**Comment by robbiecarlton** [comment]
Thanks @zippy

> 1. From what I can tell this won't actually work if used yet because [react-graphql dna pointing to the wrong place](https://github.com/holochain/react-graphql-template/blob/master/dna_src/zomes/notes/code/Cargo.toml)
> 
> I have made pull requests [here](https://github.com/holochain/holochain_anchors/pull/8) and [here](https://github.com/holochain/react-graphql-template/pull/16) that I think fix that.
> 

We're going to merge your PR into `react-graphql-template`, so then just waiting on the PR into  `holochain_anchors` to be merged.

> 1. The fn hn-happ-create does much more than create the happ, it also spins it up and runs it, which was confusing to me because you see the error logs spinning out of both a sim2h server and the recact server (I think) all the while that it's building a happ.   I would think that there should be a create step, and separate run step.

Agreed. Lisa is separating that our right now.

> 2. There are no tests for hn-happ-create itself, so we can't tell that its actually even working in the CI.  Adding tests would mean adding something like or to the test/nix-env.sh file that proves out that the command actually does what's expected.  I think that might likely be difficult/impossible given all the stuff that it fires up!  Another reason perhaps at least to split hn-happ-create into create and run?

Joel is looking into writing a test that just tests that a file called `NotesHApp.js` is created and contains some text we're expecting, as a smoke test. But if you're good with that not blocking this PR, we'll do that as a separate PR.

> I don't want to block the merge but I think that is pretty weird for something that's supposed to be intuitive to first time users. @pdaoust ?

@pdaoust - these changes will mean a small change in the installation instructions, I'll make the change to the readme

**Comment by zippy** [comment]
> Joel is looking into writing a test that just tests that a file called `NotesHApp.js` is created and contains some text we're expecting, as a smoke test. But if you're good with that not blocking this PR, we'll do that as a separate PR.

Totally, that sounds great.

>We're going to merge your PR into react-graphql-template, so then just waiting on the PR into holochain_anchors to be merged.

It's an easy merge.  @philipbeadle or @freesig should be able to confirm right away.

**Comment by pdaoust** [comment]
Minor inconsistency in the dev pulse as a result of these changes (no `cd my-notes-app` before running); fixed this morning.

**Comment by pdaoust** [comment]
@robbiecarlton I also updated the readme this morning: https://github.com/holochain/react-graphql-template/pull/15/commits/3dc3151fbbff029e9698c43fdb5d31f7502f4df9

**Pull request merged**
