### PR TITLE
github-actions: use a matrix to update scaffolding

### PR DESCRIPTION
**Pull request by steveej**

### CODE REVIEW

**Comment by jost-s** [comment]
@steveeJ It looks good to me, but since it hasn't run on a CI, I can't tell if it'll work in practice 😼 Or can I?

**Review by jost-s — COMMENTED** [review]
@steveeJ It looks good to me, but since it hasn't run on a CI, I can't tell if it'll work in practice 😼 Or can I?

**Comment by steveej** [comment]
> @steveeJ It looks good to me, but since it hasn't run on a CI, I can't tell if it'll work in practice smirk_cat Or can I?

yes indeed you can! [here's a run](https://github.com/holochain/holonix/actions/runs/1988823512) that i triggered manually using the command `nix-shell -p gh --run 'gh workflow run update-dispatch.yml --ref pr_autoupdate_scaffolding -f only-base-ref=true'` which resulted in [this PR](https://github.com/holochain/holonix/pull/352).

**Review by jost-s — APPROVED** [review]
> nix-shell -p gh --run 'gh workflow run update-dispatch.yml --ref pr_autoupdate_scaffolding -f only-base-ref=true'

"Es lag mir auf der Zunge" 😂 

Brilliant, nice one!

**Pull request merged**
