### PR TITLE
holo-nixpkgs: bump to include libiconv dependency on darwin

### PR DESCRIPTION
**Pull request by steveej**

### CODE REVIEW

**Comment by guillemcordoba** [comment]
I guess my role here is to determine whether the holochain commit hash is appropriate for developers to use it right? If so, I would say yes, but... Maybe I'd wait after the proxy merges that are coming up this week, since I've been having some issues connecting with the proxy server with the last commits on the holochain repository. Most recent commit hash I've found to work without any issues it `d3a6144`. 

Apart from that, looks good if we can get more support for the MacOs people :D

**Comment by steveej** [comment]
@guillemcordoba I think it's okay if the `develop` branch isn't perfect. I want to unblock the macOS devs with this PR so they can compile non-trivial happs. I do find your feedback highly valuable and I'm actively thinking about a way to make the `main` branch (holochain.love) the recommended version for all non-core devs.

As you know you can still pin a different holochain version and benefit from the new dependencies from here. WDYT?

**Comment by guillemcordoba** [comment]
Awesome, then let's go ahead with this one!

**Comment by guillemcordoba** [comment]
Oh wait I think I can approve but it doesn't count because I don't have write access.

**Review by guillemcordoba — APPROVED** [review]

**Comment by stephenpurkiss** [comment]
In https://github.com/holochain/holonix/issues/211#issuecomment-804890719:

> In the meantime we merged something that will likely help with the libiconv linking, see #212. You could help us confirm that using nix-shell https://nightly.holochain.love as your entrypoint into the shell.

Catalina 10.15.7 on 2012 MBPro - `nix-shell https://nightly.holochain.love` works fine.

FYI:

`CARGO_TARGET_DIR=target cargo build --release --target wasm32-unknown-unknown`

works fine

However this time when I run `./run_tests` instead of saying `./run_tests: line 2: hc: command not found` it does this then just sits there, and it's late so I'm presuming it's not going any further:

```
[nix-shell:~/Holoplay/developer-exercises/basic/0.entries]$ ./run_tests
Wrote bundle /Users/steve/Holoplay/developer-exercises/basic/0.entries/workdir/exercise.dna

> core-js@2.6.12 postinstall /Users/steve/Holoplay/developer-exercises/basic/0.entries/tests/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN demo-1@0.0.0 No description
npm WARN demo-1@0.0.0 No repository field.

added 175 packages from 205 contributors and audited 178 packages in 8.559s

39 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

> demo-1@0.0.0 test /Users/steve/Holoplay/developer-exercises/basic/0.entries/tests
> TRYORAMA_LOG_LEVEL=info RUST_LOG=error RUST_BACKTRACE=1 TRYORAMA_HOLOCHAIN_PATH="holochain" ts-node src/index.ts

23:19:17 [tryorama] info: Using the following settings from environment variables:
23:19:17 [tryorama] info: {
  "adminInterfaceId": "tryorama-interface-admin",
  "appInterfaceId": "tryorama-interface-app",
  "stateDumpOnError": true,
  "zomeCallTimeoutMs": 90000,
  "conductorTimeoutMs": 125000,
  "strictConductorTimeout": false,
  "chooseFreePort": false,
  "logLevel": "info",
  "portRange": [
    33000,
    34000
  ],
  "legacy": false,
  "singletonAppId": "TRYORAMA_APP",
  "holochainPath": "holochain",
  "lairPath": "lair-keystore"
}
TAP version 13
# say a greeting
FIXME: ignoring onJoin
23:19:17 [tryorama] info: Spawning lair for test with keystore at:  /tmp/tmp.7piJmwSLQL/tryorama/WP7RVo/keystore
23:19:17 [tryorama] info: Using conductor path:  holochain
23:19:17 [tryorama] info: Holochain version:     holochain 0.0.100

23:19:17 [tryorama] info: Conductor config path: /tmp/tmp.7piJmwSLQL/tryorama/WP7RVo/conductor-config.yml
23:19:17 info:
☉☉☉ [[[CONDUCTOR c0]]]
☉
☉ The specified config file (/tmp/tmp.7piJmwSLQL/tryorama/WP7RVo/conductor-config.yml)
☉ could not be parsed, because it is not valid YAML. Please check and fix the
☉ file, or delete the file and run the conductor again with the -i flag to create
☉ a valid default configuration. Details:
☉
☉     network: missing field `network_type` at line 2 column 17
☉
☉
☉
23:19:17 [tryorama] info: conductor 'c0' exited with code 42
23:19:17 [tryorama] error: Test error: 'Conductor exited before starting interface (code 42)'
not ok 1 Test threw an exception. See output for details.
  ---
    operator: fail
    at: <anonymous> (/Users/steve/Holoplay/developer-exercises/basic/0.entries/tests/node_modules/@holochain/tryorama/src/middleware.ts:137:13)
    stack: |-
      Error: Test threw an exception. See output for details.
          at Test.assert [as _assert] (/Users/steve/Holoplay/developer-exercises/basic/0.entries/tests/node_modules/tape/lib/test.js:269:54)
          at Test.bound [as _assert] (/Users/steve/Holoplay/developer-exercises/basic/0.entries/tests/node_modules/tape/lib/test.js:90:32)
          at Test.fail (/Users/steve/Holoplay/developer-exercises/basic/0.entries/tests/node_modules/tape/lib/test.js:363:10)
          at Test.bound [as fail] (/Users/steve/Holoplay/developer-exercises/basic/0.entries/tests/node_modules/tape/lib/test.js:90:32)
          at /Users/steve/Holoplay/developer-exercises/basic/0.entries/tests/node_modules/@holochain/tryorama/src/middleware.ts:137:13
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ...
```

If I just run `nix-shell` it still errors, only reason I'm posting this here is because it breaks at `note: ld: library not found for -liconv` and:

> we merged something that will likely help with the libiconv linking

and `liconv`is only 2 characters different than `libiconv`

```
   Compiling const-random-macro v0.1.13
error: linking with `/nix/store/sw7b2gcklaj3iy5ikv7ag163bpry3ivb-clang-wrapper-7.1.0/bin/cc` failed: exit code: 1
  |
  = note: "/nix/store/sw7b2gcklaj3iy5ikv7ag163bpry3ivb-clang-wrapper-7.1.0/bin/cc" "-m64" "-arch" "x86_64" "-L" "/nix/store/mbmhlhhbcd6h3nwscfm6hyfi4g0adrvh-rust-1.48.0-2020-11-16-7eac88abb/lib/rustlib/x86_64-apple-darwin/lib" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.0.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.1.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.10.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.11.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.12.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.13.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.14.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.15.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.2.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.3.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.4.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.5.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.6.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.7.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.8.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.const_random_macro.d2zy5i9r-cgu.9.rcgu.o" "-o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/libconst_random_macro-9a902a1dd1bff001.dylib" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.bmm6ydvizzs08wt.rcgu.o" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/const_random_macro-9a902a1dd1bff001.9ffdv3kala9ku6t.rcgu.o" "-Wl,-dead_strip" "-dynamiclib" "-Wl,-dylib" "-nodefaultlibs" "-L" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps" "-L" "/nix/store/mbmhlhhbcd6h3nwscfm6hyfi4g0adrvh-rust-1.48.0-2020-11-16-7eac88abb/lib/rustlib/x86_64-apple-darwin/lib" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/libgetrandom-2c5a0339f5242cec.rlib" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/liblibc-629a0f50f5c933d3.rlib" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/libcfg_if-89ba5a4e0fc60526.rlib" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/libtiny_keccak-ce08384ede31f549.rlib" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/libcrunchy-86147ad274e5e238.rlib" "/private/tmp/tmp.7piJmwSLQL/nix-build-holochain.drv-0/source/target/release/deps/liblazy_static-149280817e49accd.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/libproc_macro-41f9768367436ba9.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/libstd-688c1376a25c049d.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-078f89c2cdb6d46b.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/libobject-fec020208bc1ad3c.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-38540dcacc9fd218.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/libgimli-6f613179f618c598.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-4d1a5d7118aaeaf2.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-d88fab3b1b9d8356.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-a21754532a052f2f.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/libunwind-2e9ebc4127641a96.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-82d0f961232a05ca.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/liblibc-370b1b71f08bac3c.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/liballoc-816106c1f35f5421.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-20f3a030f1a56a86.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/libcore-60333aa00936c5ce.rlib" "/nix/store/2gpgkccqb22gchhcvaf73li8nyq0qcvi-rust/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-116aaeaea873ef94.rlib" "-liconv" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: ld: library not found for -liconv
          clang-7: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: could not compile `const-random-macro`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
builder for '/nix/store/gjds6y8dgzkymh0sh9bd22h04ffc1h7h-holochain.drv' failed with exit code 101
error: build of '/nix/store/gjds6y8dgzkymh0sh9bd22h04ffc1h7h-holochain.drv', '/nix/store/rv1q1h55jpjdacz572pc2bk4yg4g5m69-holochain.drv' failed
```

I realise this is not an issue dealing with the exercises however thought it would be useful to post.

**Pull request merged**
