### PR TITLE
move HC_TARGET_PREFIX to TMPDIR

### LINKED ISSUE #25: HC_TARGET_PREFIX is in a dumb place
home directory is a silly place to put it

### PR DESCRIPTION
**Pull request by thedavidmeister**
fixes #25

### CODE REVIEW

**Review by lukateras — COMMENTED** [review]
Interestingly enough, `$TMPDIR` is not set on any of my Linux systems (NixOS `unstable`, Debian `buster`) while I do have it set on my macOS machine. I am not sure if this is result of my misconfiguration (although Debian image that I tested this on doesn't have anything installed on it). It's mentioned [in Unix spec](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html).

In lieu of that, there is `mktemp -d` command, which uses `$TMPDIR` if set, else `/tmp`. So it provides a fallback. Unlike approach in this PR, `mktemp -d` is going to create a different target prefix directory for each Nix shell, which could be positive or negative depending on intent (worse for build artifact reuse, better for cases when we might want to give each Nix shell its own target prefix to manage).

Is the intent not to rewrite native development environment artifacts? In that case I'd like to propose using `$PWD/target` with each platform in its own subdir. Essentially, think of:

- `target/x86_64-apple-darwin` for development builds on macOS 
- `target/x86_64-unknown-linux-gnu` for dynamic linking builds on Linux (better for development environment because there's less code being copied around, as a result, less IO, as a result, shorter feedback loop)
- `target/x86_64-unknown-linux-gnu` for statically linked production builds for Linux x86 (currently, `rustc` assumes that any use of Musl libc means output should be static)
- `target/x86_64-unknown-linux-musl` for statically linked production builds for Linux AArch64
- `target/x86_64-pc-windows-gnu` for Windows cross-compilation artifacts
- `target/wasm32-unknown-unknown` for WebAssembly

Better yet, we can check what Rust toolchain on `PATH` is targeting and derive `--target-dir` from that information.

(See platform names [here](https://forge.rust-lang.org/platform-support.html)).

**Comment by thedavidmeister** [comment]
@yegortimoshenko we are using `mktemp`

https://github.com/holochain/holonix/pull/33/files#diff-c2e0e63e3e44e247d7ac6f525423e84aR53

the `HC_TARGET_PREFIX` is something that was added a long time ago

i think it was to help co-ordinate the incremantal compilation somehow to maximise cache hits but i don't totally remember :thinking:

**Comment by lukateras** [comment]
> @yegortimoshenko we are using mktemp

Oh, right!

```
export TMP=$( mktemp -p /tmp -d )
export TMPDIR=$TMP
```

(Nit: `-p /tmp` should be redundant on POSIX compliant systems, also `-p` is not portable, e.g. see [macOS man page](https://ss64.com/osx/mktemp.html)).

> i think it was to help co-ordinate the incremantal compilation somehow to maximise cache hits but i don't totally remember thinking

Makes sense! In this case, cache hits will be reduced because `HC_TARGET_PREFIX` will change on Nix shell re-entry. Thinking, per-platform project-local prefixes should provide max cache hits.

**Comment by thedavidmeister** [comment]
@yegortimoshenko the old way it was didn't rely on `-p`

check this out https://github.com/holochain/holonix/pull/27/commits/5761f04b3a5784139f349eaf5084c965f8996a76

**Comment by thedavidmeister** [comment]
@yegortimoshenko `/tmp` is not redundant on my machine and wasn't on @neonphog 's either, see the linked issue for debug examples

**Comment by thedavidmeister** [comment]
i'm closing this as this var has been removed from this repo in favour of moving it to `holochain-rust`

but also it should still move to something under /tmp i think @zippy

**Pull request closed without merging**
